name: Daily Shorts Factory 🚀
on:
  workflow_dispatch: # تشغيل يدويا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install edge-tts requests
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Run Video Factory
        env:
          PEXELS_KEY: ${{ secrets.PEXELS_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python production_script.py
